image: tiangolo/docker-with-compose

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy
  
build-prod:
  stage: build
  script:
    - TAG=prod FRONTEND_ENV=production sh ./scripts/build-push.sh
  only:
    - master
  tags:
    - build
    - test

deploy-prod:
  stage: deploy
  script:
    - >
      DOMAIN=cpms.technion.ac.il
      TRAEFIK_TAG=cpms.technion.ac.il
      STACK_NAME=docker_swarm_stack_deploy
      TAG=prod
      sh ./scripts/deploy.sh
  environment:
    name: production
    url: https://cpms.technion.ac.il
  only:
    - master
  tags:
    - swarm
    - prod
