"""empty message

Revision ID: c58a0f3508b5
Revises: 
Create Date: 2021-01-28 17:45:39.216456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58a0f3508b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userFirstName', sa.String(length=64), nullable=False),
    sa.Column('userSecondName', sa.String(length=64), nullable=False),
    sa.Column('userFirstNameHebrew', sa.String(length=64), nullable=False),
    sa.Column('userSecondNameHebrew', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('cellPhone', sa.String(length=64), nullable=False),
    sa.Column('homePhone', sa.String(length=64), nullable=True),
    sa.Column('workPhone', sa.String(length=64), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('faculty', sa.String(length=80), nullable=False),
    sa.Column('semester', sa.String(length=80), nullable=False),
    sa.Column('course', sa.String(length=80), nullable=False),
    sa.Column('organization', sa.String(length=80), nullable=False),
    sa.Column('advisorType', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellPhone'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
