-- MySQL Script generated by MySQL Workbench
-- Sun Jun 27 11:09:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cpms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cpms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpms` DEFAULT CHARACTER SET utf8 ;
USE `cpms` ;

-- -----------------------------------------------------
-- Table `cpms`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`courses` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  `continuationOfCourse` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`organizations` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`teams` (
  `id` INT NOT NULL,
  `projectId` INT NULL DEFAULT NULL,

  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `creatorId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `projectId_idx` (`projectId` ASC),
  CONSTRAINT `teams.projectId`
    FOREIGN KEY (`projectId`)
    REFERENCES `cpms`.`projects` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`projects` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `organizationId` INT NULL DEFAULT NULL,
  `teamId` INT NULL DEFAULT NULL,
  `numOfSemesters` INT NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  `academicAdvisorId` VARCHAR(255) NULL DEFAULT NULL,
  `industrialAdvisorId` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `initiationDate` DATETIME NULL DEFAULT NULL,
  `assignDate` DATETIME NULL DEFAULT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `contactName` VARCHAR(255) NULL DEFAULT NULL,
  `contactPhone` VARCHAR(255) NULL DEFAULT NULL,
  `contactEmail` VARCHAR(255) NULL DEFAULT NULL,
  `contactIsAdvisor` TINYINT(1) NULL DEFAULT NULL,
  `approvedRequestsIds` VARCHAR(255) NULL DEFAULT NULL,
  `lastVerified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `organizationId_idx` (`organizationId` ASC),
  INDEX `teamId_idx` (`teamId` ASC),
  CONSTRAINT `projects.academiclAdvisorId`
	  FOREIGN KEY (`academicAdvisorId`)
	  REFERENCES `users` (`firebase_user_id`)
	  ON DELETE SET NULL
	  ON UPDATE CASCADE,
  CONSTRAINT `projects.industrialAdvisorId`
	  FOREIGN KEY (`industrialAdvisorId`)
	  REFERENCES `users` (`firebase_user_id`)
	  ON DELETE SET NULL
	  ON UPDATE CASCADE,
  CONSTRAINT `projects.organizationId`
    FOREIGN KEY (`organizationId`)
    REFERENCES `cpms`.`organizations` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `projects.teamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `cpms`.`teams` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`delayrequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`delayrequests` (
  `id` INT NOT NULL,
  `projectId` INT NULL DEFAULT NULL,
  `studentId` VARCHAR(255) NULL DEFAULT NULL,
  `subject` VARCHAR(255) NULL DEFAULT NULL,
  `body` VARCHAR(255) NULL DEFAULT NULL,
  `requestedDate` DATETIME NULL DEFAULT NULL,
  `answeredDate` DATETIME NULL DEFAULT NULL,
  `answer` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `teamId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `projectId_idx` (`projectId` ASC),
  INDEX `project.teamId_idx` (`teamId` ASC),
  CONSTRAINT `delayrequests.projectId`
    FOREIGN KEY (`projectId`)
    REFERENCES `cpms`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `delayrequests.teamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `cpms`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`events` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `start` DATETIME NULL DEFAULT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `type` VARCHAR(15) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  `color` VARCHAR(10) NULL DEFAULT NULL,
  `displayToAll` TINYINT(1) NULL DEFAULT NULL,
  `courseId` INT NULL DEFAULT NULL,
  `sessionTime` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `courseId_idx` (`courseId` ASC),
  CONSTRAINT `events.courseId`
    FOREIGN KEY (`courseId`)
    REFERENCES `cpms`.`courses` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`genericitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`genericitems` (
  `id` INT NOT NULL,
  `header` VARCHAR(255) NULL DEFAULT NULL,
  `body` VARCHAR(255) NULL DEFAULT NULL,
  `fileId` INT NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,

  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`files` (
  `id` INT NOT NULL,
  `projectId` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `fileComponentId` VARCHAR(255) NULL DEFAULT NULL,
  `itemId` INT NULL DEFAULT NULL,
  `teamId` INT NULL DEFAULT NULL,
  `numOfUpdates` INT NOT NULL DEFAULT '0',
  `submissionDate` DATETIME NULL DEFAULT NULL,
  `deadline` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `projectId_idx` (`projectId` ASC),
  INDEX `files.itemId_idx` (`itemId` ASC),
  INDEX `files.teamId_idx` (`teamId` ASC),
  CONSTRAINT `files.itemId`
    FOREIGN KEY (`itemId`)
    REFERENCES `cpms`.`genericitems` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `files.projectId`
    FOREIGN KEY (`projectId`)
    REFERENCES `cpms`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `files.teamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `cpms`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`projectproposals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`projectproposals` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  `organizationId` INT NULL DEFAULT NULL,
  `numOfSemesters` INT NULL DEFAULT NULL,
  `contactName` VARCHAR(255) NULL DEFAULT NULL,
  `contactPhone` VARCHAR(255) NULL DEFAULT NULL,
  `contactEmail` VARCHAR(255) NULL DEFAULT NULL,
  `contactIsAdvisor` TINYINT(1) NULL DEFAULT NULL,
  `initiationDate` DATETIME NULL DEFAULT NULL,
  `academicAdvisorId` VARCHAR(255) NULL DEFAULT NULL,
  `industrialAdvisorId` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
    CONSTRAINT `projectproposals.organizationId`
    FOREIGN KEY (`organizationId`)
    REFERENCES `cpms`.`organizations` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `projectproposals.academiclAdvisorId`
	  FOREIGN KEY (`academicAdvisorId`)
	  REFERENCES `users` (`firebase_user_id`)
	  ON DELETE SET NULL
	  ON UPDATE CASCADE,
  CONSTRAINT `projectproposals.industrialAdvisorId`
	  FOREIGN KEY (`industrialAdvisorId`)
	  REFERENCES `users` (`firebase_user_id`)
	  ON DELETE SET NULL
	  ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`schedule` (
  `id` INT NOT NULL,
  `time` VARCHAR(20) NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `projectId` INT NULL DEFAULT NULL,
  `eventId` INT NULL DEFAULT NULL,
  `teamId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `eventId_idx` (`eventId` ASC),
  INDEX `schedule.projectId_idx` (`projectId` ASC),
  INDEX `schedule.teamId_idx` (`teamId` ASC),
  CONSTRAINT `schedule.eventId`
    FOREIGN KEY (`eventId`)
    REFERENCES `cpms`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `schedule.projectId`
    FOREIGN KEY (`projectId`)
    REFERENCES `cpms`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `schedule.teamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `cpms`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`semesters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`semesters` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `startDate` DATETIME NULL DEFAULT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `isCurrent` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`studentsfindpartners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`studentsfindpartners` (
  `id` INT NOT NULL,
  `student` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`teamsfindpartners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`teamsfindpartners` (
  `id` INT NOT NULL,
  `student` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`teamsprojectsrequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`teamsprojectsrequests` (
  `id` INT NOT NULL,
  `teamId` INT NULL DEFAULT NULL,
  `projectId` INT NULL DEFAULT NULL,
  `adminStatus` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `teamId` (`teamId` ASC),
  INDEX `projectId_idx` (`projectId` ASC),
  CONSTRAINT `teamsprojectsrequests.projectId`
    FOREIGN KEY (`projectId`)
    REFERENCES `cpms`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teamsprojectsrequests.teamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `cpms`.`teams` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`personel_cpms2011`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`personel_cpms2011` (
  `id` int NOT NULL,
  `prefix` varchar(255) DEFAULT NULL,
  `advisorType` varchar(255) DEFAULT NULL,
  `engFirstName` varchar(255) DEFAULT NULL,
  `engLastName` varchar(255) DEFAULT NULL,
  `hebFirstName` varchar(255) DEFAULT NULL,
  `hebLastName` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `workPhone` varchar(255) DEFAULT NULL,
  `cellPhone` varchar(255) DEFAULT NULL,
  `organizationId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `cpms`.`projects_cpms2011`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`projects_cpms2011` (
  `id` int NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `organizationName` varchar(255) DEFAULT NULL,
  `teamId` int(11) DEFAULT NULL,
  `numOfSemesters` int(11) DEFAULT NULL,
  `description` varchar(5000) DEFAULT NULL,
  `academicAdvisorId` varchar(255) DEFAULT NULL,
  `industrialAdvisorId` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `initiationDate` datetime DEFAULT NULL,
  `assignDate` datetime DEFAULT NULL,
  `endDate` datetime DEFAULT NULL,
  `contactName` varchar(255) DEFAULT NULL,
  `contactPhone` varchar(255) DEFAULT NULL,
  `contactEmail` varchar(255) DEFAULT NULL,
  `contactIsAdvisor` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `cpms`.`teams_cpms2011` (
  `id` int(11) NOT NULL,
  `students` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `cpms`.`genericitemtocourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`genericitemtocourse` (
  `genericItemId` INT NULL DEFAULT NULL,
  `courseId` INT NULL DEFAULT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `getericItemId_idx` (`genericItemId` ASC),
  INDEX `courseId_idx` (`courseId` ASC),
  CONSTRAINT `genericitemtocourse.getericItemId`
    FOREIGN KEY (`genericItemId`)
    REFERENCES `cpms`.`genericitems` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `genericitemtocourse.courseId`
    FOREIGN KEY (`courseId`)
    REFERENCES `cpms`.`courses` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpms`.`users` (
  `firebase_user_id` VARCHAR(255) NOT NULL,
  `id` INT NULL DEFAULT NULL,
  `hebFirstName` VARCHAR(255) NULL DEFAULT NULL,
  `hebLastName` VARCHAR(255) NULL DEFAULT NULL,
  `engFirstName` VARCHAR(255) NULL DEFAULT NULL,
  `engLastName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `cellPhone` VARCHAR(255) NULL DEFAULT NULL,
  `workPhone` VARCHAR(255) NULL DEFAULT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT NULL,
  `prefix` VARCHAR(255) NULL DEFAULT NULL,
  `user_type` VARCHAR(255) NULL DEFAULT NULL,
  `organizationId` INT NULL DEFAULT NULL,
  `advisorType` VARCHAR(255) NULL DEFAULT NULL,
  `faculty` VARCHAR(255) NULL DEFAULT NULL,
  `semesterId` INT NULL DEFAULT NULL,
  `courseId` INT NULL DEFAULT NULL,
  `teamId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`firebase_user_id`),
  CONSTRAINT `users.organizationId`
    FOREIGN KEY (`organizationId`)
    REFERENCES `cpms`.`organizations` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `users.semesterId`
    FOREIGN KEY (`semesterId`)
    REFERENCES `cpms`.`semesters` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `users.courseId`
    FOREIGN KEY (`courseId`)
    REFERENCES `cpms`.`courses` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `users.teamId`
    FOREIGN KEY (`teamId`)
    REFERENCES `cpms`.`teams` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpms`.`syllabusconfirmation`
-- -----------------------------------------------------
CREATE TABLE `cpms`.`syllabusconfirmation` (
  `id` VARCHAR(255) NOT NULL,
  `confirmation` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `syllabusconfirmation.id`
    FOREIGN KEY (`id`)
    REFERENCES `cpms`.`users` (`firebase_user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;